#!/bin/bash


start_emulator(){
  kill -9 $(lsof -t  -i udp:33309)
  kill -9 $(lsof -t  -i udp:10226)
  python3 network_emulator.py  33309 10.15.154.51 14106 10226 10.15.154.52 57512 20 0.1 1

}

cd nEmulator
start_emulator

