#!/bin/bash

send_8packets(){
  kill -9 $(lsof -t  -i udp:53718)
  python3 send.py 129.97.167.46 56518 53718 400 fileSent8Packets.txt
}

send_45packets(){
  kill -9 $(lsof -t  -i udp:53718)
  python3 send.py 129.97.167.46 56518 53718 400 fileSent45Packets.txt
}



cd RDTSender

i="0"

while [ $i -lt 10 ]
do
  sleep 1
  send_45packets
  i=$[$i+1]
done